# Generated by Django 2.0.9 on 2018-10-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0003_featuredcontentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcontentpage',
            name='featured_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
