# Generated by Django 2.0.9 on 2018-10-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('realblog', '0006_featuredcontentpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcontentpage',
            name='featured_page',
        ),
        migrations.RemoveField(
            model_name='featuredcontentpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FeaturedContentPage',
        ),
    ]
