# Generated by Django 2.0.9 on 2018-10-16 12:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0010_auto_20181016_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('first_paragraph', wagtail.core.blocks.RichTextBlock(template='realblog/blocks/para_caps.html')), ('paragraph', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
