# Generated by Django 2.0.9 on 2018-10-16 17:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0015_auto_20181016_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('first_paragraph', wagtail.core.blocks.CharBlock()), ('code', wagtail.core.blocks.CharBlock()), ('pullquotes', wagtail.core.blocks.CharBlock()), ('blockquotes', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock()), ('cite', wagtail.core.blocks.CharBlock()), ('cite_link', wagtail.core.blocks.URLBlock())], template='blocks/bquote.html')), ('paragraph', wagtail.core.blocks.RichTextBlock())]),
        ),
    ]
