# Generated by Django 2.0.9 on 2018-10-16 18:13

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realblog', '0017_auto_20181016_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('first_paragraph', wagtail.core.blocks.CharBlock()), ('pullquotes', wagtail.core.blocks.CharBlock()), ('blockquotes', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock()), ('cite', wagtail.core.blocks.CharBlock()), ('cite_link', wagtail.core.blocks.URLBlock(required=False))], template='blocks/bquote.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], help_text='Coding language', label='Language')), ('code', wagtail.core.blocks.TextBlock(label='Code'))]))]),
        ),
    ]
